################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../emlib/em_assert.c \
../emlib/em_cmu.c \
../emlib/em_core.c \
../emlib/em_emu.c \
../emlib/em_gpio.c \
../emlib/em_lcd.c \
../emlib/em_rtc.c \
../emlib/em_system.c \
../emlib/em_usart.c \
../emlib/segmentlcd.c 

OBJS += \
./emlib/em_assert.o \
./emlib/em_cmu.o \
./emlib/em_core.o \
./emlib/em_emu.o \
./emlib/em_gpio.o \
./emlib/em_lcd.o \
./emlib/em_rtc.o \
./emlib/em_system.o \
./emlib/em_usart.o \
./emlib/segmentlcd.o 

C_DEPS += \
./emlib/em_assert.d \
./emlib/em_cmu.d \
./emlib/em_core.d \
./emlib/em_emu.d \
./emlib/em_gpio.d \
./emlib/em_lcd.d \
./emlib/em_rtc.d \
./emlib/em_system.d \
./emlib/em_usart.d \
./emlib/segmentlcd.d 


# Each subdirectory must supply rules for building sources it contributes
emlib/em_assert.o: ../emlib/em_assert.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/em_assert.d" -MT"emlib/em_assert.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

emlib/em_cmu.o: ../emlib/em_cmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/em_cmu.d" -MT"emlib/em_cmu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

emlib/em_core.o: ../emlib/em_core.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/em_core.d" -MT"emlib/em_core.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

emlib/em_emu.o: ../emlib/em_emu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/em_emu.d" -MT"emlib/em_emu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

emlib/em_gpio.o: ../emlib/em_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/em_gpio.d" -MT"emlib/em_gpio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

emlib/em_lcd.o: ../emlib/em_lcd.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/em_lcd.d" -MT"emlib/em_lcd.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

emlib/em_rtc.o: ../emlib/em_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/em_rtc.d" -MT"emlib/em_rtc.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

emlib/em_system.o: ../emlib/em_system.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/em_system.d" -MT"emlib/em_system.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

emlib/em_usart.o: ../emlib/em_usart.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/em_usart.d" -MT"emlib/em_usart.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

emlib/segmentlcd.o: ../emlib/segmentlcd.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DGCC_ARMCM3=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DDEBUG=1' -I"C:/Users/sebokbence/SimplicityStudio/v4_workspace_2/GeckoCLI/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//app/mcu_example/EFM32GG_STK3700/freertos_blink" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/EFM32GG_STK3700/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/CMSIS/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emlib/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/common/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ezradiodrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/config" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/drivers" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/dmadrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/gpiointerrupt/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/nvm/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/rtcdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/sleep/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/spidrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/uartdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/ustimer/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/emdrv/tempdrv/inc" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//hardware/kit/common/bsp" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//platform/Device/SiliconLabs/EFM32GG/Include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Demo/Common/include" -I"F:/dev/Simplicity/developer/sdks/gecko_sdk_suite/v1.1//util/third_party/freertos/Source/portable/GCC/ARM_CM3" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"emlib/segmentlcd.d" -MT"emlib/segmentlcd.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


